osx_image: xcode8.3
language: objective-c
script:
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme CocoaHTTPServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme DynamicServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme iPhoneHTTPServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme PasswdHTTPServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme PostHTTPServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme SecureHTTPServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme SecureWebSocketServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme SimpleFileUploadServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme SimpleHTTPServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme SimpleWebSocketServer
  - xcodebuild build -workspace CocoaHTTPServer.xcworkspace -scheme WebDAVServer
